name: Docker Image security scan

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    trivy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4.2.2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.11.1
              
            - name: Build docker image
              run: docker build -t hardening-project-v2 . 

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: 'hardening-project-v2'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                severity: 'MEDIUM,CRITICAL,HIGH'
    